"""add_tg_id_column

Revision ID: cf6c45081c57
Revises: 9eebe0ba281a
Create Date: 2026-02-15 09:34:24.345690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6c45081c57'
down_revision: Union[str, Sequence[str], None] = '9eebe0ba281a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_url'), 'products', ['url'], unique=True)
    op.drop_constraint(op.f('uq_user_product'), 'subscriptions', type_='unique')
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('subscriptions_product_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('tg_chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_chat_id')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_product_id_fkey'), 'subscriptions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_product'), 'subscriptions', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_products_url'), table_name='products')
    # ### end Alembic commands ###
